name: Production Release
on:
    workflow_dispatch:
jobs:
    feature-test:
        name: "Production Release"
        uses: muselab-d2x/d2x/.github/workflows/release-.yml@cumulusci-next
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"
            
